version: '3.7'

services:
  mongodb:
    container_name: events-db
    image: mongo:6.0.6
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${DEFAULT_DB}
    volumes:
      - dev-db:/data/db
      - ../scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  api:
    container_name: conference-bff
    image: ${COMPOSE_PROJECT_NAME}:latest
    ports:
      - '5002:5002'
    platform: ${PLATFORM}
    tty: true
    depends_on:
      - mongodb
    environment:
      # TODO: This guys need to be refactored
      - NODE_ENV=production
      - AUTH_URI=${AUTH_URI}
      - TOKEN_URI=${TOKEN_URI}
      - MONGODB_URI=${MONGODB_URI}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_ROOT_USERNAME=${DB_ROOT_USERNAME}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DEFAULT_DB=${DEFAULT_DB}
      - PORT=${PORT}
      - AUTH_PROVIDER_CERT_URL=${AUTH_PROVIDER_CERT_URL}
      - AUTH_PRIVATE_KEY_ID=${AUTH_PRIVATE_KEY_ID}
      - AUTH_PRIVATE_KEY=${AUTH_PRIVATE_KEY}
      - AUTH_CLIENT_EMAIL=${AUTH_CLIENT_EMAIL}
      - AUTH_CLIENT_ID=${AUTH_CLIENT_ID}
      - AUTH_CLIENT_CERT_URL=${AUTH_CLIENT_CERT_URL}
      - AUTH_API_KEY=${AUTH_API_KEY}
      - AUTH_DOMAIN=${AUTH_DOMAIN}
      - AUTH_PROJECT_ID=${AUTH_PROJECT_ID}
      - AUTH_STORAGE_BUCKET=${AUTH_STORAGE_BUCKET}
      - AUTH_MESSAGING_SENDER_ID=${AUTH_MESSAGING_SENDER_ID}
      - AUTH_APP_ID=${AUTH_APP_ID}
      - AUTH_MEASUREMENT_ID=${AUTH_MEASUREMENT_ID}
      - PRIVATE_KEY_V2=${PRIVATE_KEY_V2}
      - PRIVATE_KEY_ADMIN_V2=${PRIVATE_KEY_ADMIN_V2}
    links:
      - mongodb

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}-network

volumes:
  dev-db:
    name: ${COMPOSE_PROJECT_NAME}-dev-db
