---
name: Check Pull Request

on: [pull_request] # yamllint disable-line rule:truthy

# env:
#   OS_VERSION: ubuntu-22.04

jobs:
  unit_test:
    runs-on: ubuntu-20.04
    # needs: ['yaml_lint', 'markdown_lint', 'docker_lint', 'eslint_lint']
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: yarn
      - name: Run Unit Tests
        run: yarn test

  megalinter:
    name: Lint Code with MegaLinter
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      # Git Checkout
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # If you use VALIDATE_ALL_CODEBASE = true, you can remove this line to improve performances

      - name: MegaLinter
        id: ml
        continue-on-error: true
        uses: oxsecurity/megalinter@v7.9.0
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} # Validates all source when push on main, else just the git diff with main. Override with true if you always want to lint all sources
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE: COPYPASTE,SPELL # Uncomment to disable copy-paste and spell checks
